name: Deploy

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: "./webapp"
      run: npm ci

    # - name: Run the tests and generate coverage report
    #   run: npm test -- --coverage

    - name: Build
      working-directory: "./webapp"
      run: npm run build


   
    - name: Deploy to GitHub 
      id: deployment
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: "./webapp/build"