name: Deploy

on:
  push:
    branches: [ main-legacy ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: "./webapp"
      run: npm ci

    # - name: Run the tests and generate coverage report
    #   run: npm test -- --coverage

    - name: Build
      working-directory: "./webapp"
      run: npm run build

    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './webapp/build'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
